<?php

namespace Tests\Feature\Auth;

use App\Models\User;
use App\Providers\RouteServiceProvider;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;


/**
 *  Automatically generated by Breeze, not working yet.
 *  Needs fine tuning to kurenai's architecture.
 * 
 */
class AuthenticationTest extends TestCase
{
    use RefreshDatabase;

    public function test_login_screen_can_be_rendered()
    {
        $response = $this->get('/services/login');

        $response->assertStatus(200);
    }

    public function test_users_can_authenticate_using_the_login_screen()
    {
        $user = User::factory()->create();

        $response = $this->post('/forms/login', [
            'password' => 'password',
            'name' => 'testUser',
        ]);

        $this->assertAuthenticated();
        $response->assertRedirect(RouteServiceProvider::HOME);
    }

    public function test_users_can_not_authenticate_with_invalid_password()
    {
        $user = User::factory()->create();

        $this->post('/forms/login', [
            'name' => $user->name, // modified, may glitch out
            'password' => 'wrong-password',
        ]);

        $this->assertGuest();
    }
}
